Us 15/database
fga-eps-mds/2021.1-PCTs-Documents-API pull request #8
Opened 2021-09-19 22:26 UTC by caiovfernandes

## Neste Pull Request se realizou:

* Adição de Model, Serializer e ViewSet das entidades:
1. Informacao;
2. Glossario.
<br>

* Configuração de rotas em ViewSets diferentes para cada model dentro da app documents.
<br>

De acordo com a modelagem definida no [documento de arquitetura](https://fga-eps-mds.github.io/2021.1-PCTs-Docs/#/product/architecture)

2021-09-20 13:40 UTC, Miguel-Alves approved these changes
Após revisar este PR, aprovo as mudanças realizadas e concordo que estão em acordo com os critérios estabelecidos e a necessidade do projeto descrita nos documentos.

2021-09-21 10:22 UTC, Ridersk requested changes
Além dos comentários que deixei nos trechos de código. Tem uma questão maior que precisa ser corrigida agora. Até o momento, devido a indecisão de qual seria o banco da API de documentos, o mesmo ainda se encontra com o sqlite como padrão. Precisa ser configurado o Postgres ou o MongoDB como já conversamos em outra reunião sobre a arquitetura.

2021-09-21 10:22 UTC, Ridersk commented on documents/models.py
> +    fonte = models.CharField(max_length=240)
Não sei o restante do grupo, mas acho que "Document" representa melhor do que se trata o registro que está sendo gravado na API

2021-09-21 10:22 UTC, Ridersk commented on documents/models.py
> +    fonte = models.CharField(max_length=240)
Outra coisa, acho que deveriamos alinhadar em relação ao idioma padrão do projeto. No Scraper por exemplo, estou fazendo o código em inglês. Acredito que deveriamos conversar sobre isso

2021-09-25 19:44 UTC, Ridersk approved these changes

2021-09-26 18:46 UTC, lucasgomesgs0 approved these changes

2021-09-26 20:55 UTC, merged